### ISSUE TITLE
gedit-code-assistance

### ISSUE THREAD

**Issue by nacho** [brvier/gedit_flake8#3]
Hi,

I see that your plugin pretends to do more or less the same as the python backend for gedit-code-assistance. Have you thought about checking if something is missing from what you have here implemented and integrate it with gedit-code-assistance?

See: http://git.gnome.org/browse/gedit-code-assistance

Regards.

**Comment by brvier** [comment]
Hi,

It s not really the same, the python backend of gedit validate only  that
the syntax of code is byte compilable by the python compiler by using ast
default python module (_http://docs.python.org/2/library/ast.html)_.

Mine plugin use flake8, a code checking tool (syntax error, warning about
PEP8, warning about uninstancied variables).

See more informations about flake8 on http://pypi.python.org/pypi/flake8/

Regards

2012/12/14 Ignacio Casal Quinteiro notifications@github.com

> Hi,
> 
> I see that your plugin pretends to do more or less the same as the python
> backend for gedit-code-assistance. Have you thought about checking if
> something is missing from what you have here implemented and integrate it
> with gedit-code-assistance?
> 
> See: http://git.gnome.org/browse/gedit-code-assistance
> 
> Regards.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/khertan/gedit_flake8/issues/3.

## 

Benoît HERVIER - http://khertan.net/

**Comment by nacho** [comment]
yes I know they are different but can't be integrated?

**Comment by brvier** [comment]
They probably could be merged, from what i quickly see from the gnome git
repository.
But what my plugin does is launching the flake8 command line and parsing
the results to display them in gedit, so it ll be probably more efficient
to directly rewrite that part in c/vala.

i should try your plugin to see what it does but i first look at building
it result in a : configure: error: cannot find install-sh, install.sh, or
shtool in "." "./.." "./../.."
And i'm currently a too busy to look at that now

Regards,

2012/12/14 Ignacio Casal Quinteiro notifications@github.com

> yes I know they are different but can't be integrated?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/khertan/gedit_flake8/issues/3#issuecomment-11373846.

## 

Benoît HERVIER - http://khertan.net/
